# Generated by Django 4.0.3 on 2022-12-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='vehicle_vin',
            new_name='auto_vin',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
