# Generated by Django 4.0.3 on 2022-12-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_appointment_auto_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='auto_vin',
        ),
    ]
