# Generated by Django 4.0.3 on 2022-12-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_remove_appointment_auto_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vehicle_vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
