# Generated by Django 4.0.3 on 2022-12-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_appointment_vehicle_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='vehicle_vin',
        ),
        migrations.AddField(
            model_name='appointment',
            name='auto_vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
